t = input("Digite algo: ")
print(type(t))
print(t.isalnum())
print(t.isalpha())
print(t.isdecimal())
print(t.isdigit())
print(t.islower())
print(t.isnumeric())
print(t.isprintable())
print(t.isspace())
print(t.istitle())
print(t.isupper())
