m = input('Digite algo: ')
print(f'O tipo é {type(m)}')
print(f'É um numero? {m.isnumeric()}')
print(f'É maisculo? {m.isupper()}')
print(f'É minusculo? {m.islower()}')
print(f'É alfabeto? {m.isalpha()}')
print(f'É decimal? {m.isdecimal()}')
print(f'É digito? {m.isdigit()}')
print(f'É alfanumerico? {m.isalnum()}')
print(f'É printavel? {m.isprintable()}')
