n = int(input('Digite um numero: '))
print(f'A tabuada do numero {n} é: ')
print('-'*14)
print(f' {n} x {1:2} = {n*1}  | \n {n} x {2:2} = {n*2} | \n {n} x {3:2} = {n*3} | \n {n} x {4:2} = {n*4} | \n {n} x {5:2} = {n*5} | \n {n} x {6:2} = {n*6} | \n {n} x {7:2} = {n*7} | \n {n} x {8:2} = {n*8} | \n {n} x {9:2} = {n*9} | \n {n} x {10} = {n*10} |')
print('-'*14)